# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearbyRestaurants' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearbyRestaurants
pod 'SDWebImage', '~> 5.0'
pod 'GoogleMaps'

  target 'NearbyRestaurantsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearbyRestaurantsUITests' do
    # Pods for testing
  end

end
